apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liron-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  # Optional: specify your storage class, or omit for default
  # storageClassName: standard
